### ISSUE TITLE
(Protobuf.DecodeError) wrong wire_type for nested_type: got 0, want 2

### ISSUE THREAD

**Issue by bbenph** [elixir-protobuf/protobuf#155]
hi i try follow the readme.md to create a demo when i execute the command it failed

> protoc --elixir_out=plugins=grpc:./lib/  .\sample_app.proto

```
** (Protobuf.DecodeError) wrong wire_type for nested_type: got 0, want 2
    (protobuf 0.7.1) lib/protobuf/decoder.ex:199: Protobuf.Decoder.build_struct/3 
    (protobuf 0.7.1) lib/protobuf/decoder.ex:15: Protobuf.Decoder.decode/2        
    (protobuf 0.7.1) lib/protobuf/decoder.ex:152: Protobuf.Decoder.build_struct/3 
    (protobuf 0.7.1) lib/protobuf/decoder.ex:15: Protobuf.Decoder.decode/2        
    (protobuf 0.7.1) lib/protobuf/decoder.ex:152: Protobuf.Decoder.build_struct/3 
    (protobuf 0.7.1) lib/protobuf/decoder.ex:15: Protobuf.Decoder.decode/2        
    (protobuf 0.7.1) lib/protobuf/protoc/cli.ex:30: Protobuf.Protoc.CLI.main/1    
    (elixir 1.11.4) lib/kernel/cli.ex:124: anonymous fn/3 in Kernel.CLI.exec_fun/2
--elixir_out: protoc-gen-elixir: Plugin failed with status code 1.
```

my mix.exs
```
defmodule Grpcdemo.MixProject do
  use Mix.Project

  def project do
    [
      app: :grpcdemo,
      version: "0.1.0",
      elixir: "~> 1.11",
      start_permanent: Mix.env() == :prod,
      deps: deps()
    ]
  end

  # Run "mix help compile.app" to learn about applications.
  def application do
    [
      extra_applications: [:logger],
      mod: {Grpcdemo.Application, []}
    ]
  end

  # Run "mix help deps" to learn about dependencies.
  defp deps do
    [
      # {:dep_from_hexpm, "~> 0.3.0"},
      # {:dep_from_git, git: "https://github.com/elixir-lang/my_dep.git", tag: "0.1.0"}
      {:protobuf, "~> 0.7.1"},
      # Only for files generated from Google's protos.
      # Can be ignored if you don't use Google's protos.
      # Or you can generate the code by yourself.
      {:google_protos, "~> 0.1"}
    ]
  end
end

```

my computer is windows10 64bits
the protoc version is  `libprotoc 3.17.0`

what can i do to use the command correctly ?

**Comment by britto** [comment]
Hi @bbenph! Could you share the `sample_app.proto` file you used to reproduce the issue?
