### ISSUE TITLE
Encoded data is not decodeable

### ISSUE THREAD

**Issue by avillen** [elixir-protobuf/protobuf#295]
I'm facing a situation where the encoded data is not decodeable. To reproduce that I'm doing:
```
Mix.new([:protobuf])
defmodule Helloworld do
    defmodule HelloRequest do
      use Protobuf, protoc_gen_elixir_version: "0.10.0", syntax: :proto3

      field(:name, 0, optional: true, type: :string)
    end
  end
struct = Helloworld.HelloRequest.new(name: "Álvaro")
encoded = Helloworld.HelloRequest.encode(struct)
Helloworld.HelloRequest.decode(encoded)
```

The last command returns this error:

```
** (Protobuf.DecodeError) invalid field number 0 when decoding binary data
    (protobuf 0.10.0) lib/protobuf/decoder.ex:48: Protobuf.Decoder.build_message/3
    (protobuf 0.10.0) lib/protobuf/decoder.ex:17: Protobuf.Decoder.decode/2
```

Using `0.9.0` ends with the same result:

```
Mix.install([{:protobuf, "~> 0.9.0"}])
defmodule Helloworld do
    defmodule HelloRequest do
      use Protobuf, syntax: :proto3

      defstruct [:name]

      field(:name, 0, optional: true, type: :string)
    end
  end
struct = Helloworld.HelloRequest.new(name: "Álvaro")
encoded = Helloworld.HelloRequest.encode(struct)
Helloworld.HelloRequest.decode(encoded)
```
```
** (Protobuf.DecodeError) invalid field number 0 when decoding binary data
    (protobuf 0.9.0) lib/protobuf/decoder.ex:47: Protobuf.Decoder.build_message/3
    (protobuf 0.9.0) lib/protobuf/decoder.ex:17: Protobuf.Decoder.decode/2
```

BUT, with `0.8.0` it works:

```
Mix.install([{:protobuf, "~> 0.8.0"}])
defmodule Helloworld do
    defmodule HelloRequest do
      use Protobuf, syntax: :proto3

      defstruct [:name]

      field(:name, 0, optional: true, type: :string)
    end
  end
struct = Helloworld.HelloRequest.new(name: "Álvaro")
encoded = Helloworld.HelloRequest.encode(struct)
Helloworld.HelloRequest.decode(encoded)
```
The result of the last line is `%Helloworld.HelloRequest{name: "Álvaro"}` as I was expecting.

Is this an issue? Or am I doing something wrong? Thanks in advance 😄

**Comment by avillen** [comment]
Oh, it was my fault for setting the number 0 to each field 🤦 Sorry for the noise!
