### ISSUE TITLE
Invalid field number 0 when decoding binary data

### ISSUE THREAD

**Issue by VincentRPS** [elixir-protobuf/protobuf#333]
I am currently trying to use Protobuf in one of my elixir projects but I keep getting this error:
```ex
** (Protobuf.DecodeError) invalid field number 0 when decoding binary data
    (protobuf 0.11.0) lib/protobuf/decoder.ex:48: Protobuf.Decoder.build_message/3
    (protobuf 0.11.0) lib/protobuf/decoder.ex:17: Protobuf.Decoder.decode/2
    (protobuf 0.11.0) lib/protobuf/decoder.ex:231: Protobuf.Decoder.value_for_field/3
    (protobuf 0.11.0) lib/protobuf/decoder.ex:382: Protobuf.Decoder.update_in_message/3
    (protobuf 0.11.0) lib/protobuf/decoder.ex:176: Protobuf.Decoder.handle_value/6
    (protobuf 0.11.0) lib/protobuf/decoder.ex:17: Protobuf.Decoder.decode/2
    (protobuf 0.11.0) lib/protobuf/decoder.ex:231: Protobuf.Decoder.value_for_field/3
    (protobuf 0.11.0) lib/protobuf/decoder.ex:382: Protobuf.Decoder.update_in_message/3
--elixir_out: protoc-gen-elixir: Plugin failed with status code 1.
```
I've looked everywhere for a solution but seemingly can't find one.

This is my Protobuf code:

```proto
syntax = "proto3";

import "google/protobuf/any.proto";

package derailed.grpc;

service Guild {
    rpc publish (Publ) returns (Publr) {};
    rpc get_guild_info (GetGuildInfo) returns (RepliedGuildInfo) {};
}

message Message {
    string event = 1;
    map<string, google.protobuf.Any> data = 2;
}

message Publ {
    string guild_id = 1;
    Message message = 2;
}

message Publr {
    string message = 1;
}

message GetGuildInfo {
    string guild_id = 1;
}

message RepliedGuildInfo {
    int32 presences = 1;
}

```

**Comment by whatyouhide** [comment]
Thanks for the report! Can you provide a minimal set of steps to reproduce the error? The Protobuf schema helps, but I'd like to have a small script that reproduces this 🙃

**Comment by VincentRPS** [comment]
> Thanks for the report! Can you provide a minimal set of steps to reproduce the error? The Protobuf schema helps, but I'd like to have a small script that reproduces this 🙃

sorry for the late response, was busy with some things. All I did was run `protoc --elixir_out=./lib {the_proto}.proto` like in the example. I don't really know what could be causing this.

I recently just reinstalled both Erlang and Elixir and even that didn't do anything. I am on Windows but I really doubt that's is the problem. It seems like the problem is occurring on this line (Protobuf.Decoder:382):

```ex
Map.put(message, key, update_fun.(current))
```

**Comment by harshrajsinha** [comment]
I am trying to read message from Kafka topic. Topic format is protobuf.

I am getting following error:  "DecodeError: Field number 0 is illegal."

I am attaching the proto file and pb2 generated:
[optiontrade - Copy.txt](https://github.com/elixir-protobuf/protobuf/files/15244114/optiontrade.-.Copy.txt)
[optiontrade_pb2 - Copy.py.txt](https://github.com/elixir-protobuf/protobuf/files/15244117/optiontrade_pb2.-.Copy.py.txt)

pb2 file is generated using following command:
protoc --python_out=C:\DAAS\test\pyi_out --proto_path=C:\DAAS\test\ C:\DAAS\test\optiontrade.proto

Below is the python code I am using:

Thanks for your help

`from confluent_kafka import Consumer, KafkaError
import os
import sys

from kafka import KafkaConsumer
os.environ["PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION"]="python"
PROTOBUF_OUT_LOC = 'C:\\DAAS\\test\\pyi_out'
if PROTOBUF_OUT_LOC:
    sys.path.append(PROTOBUF_OUT_LOC)

    # List all files in the shared location
    files = os.listdir(PROTOBUF_OUT_LOC)

    # Filter out files that are Python modules
    python_files = [f for f in files if f.endswith('.py')]

    # Import each Python file dynamically
    for py_file in python_files:
        module_name = os.path.splitext(py_file)[0]
        module = __import__(module_name)
        globals()[module_name] = module

def decode_message(message_value):
    # Parse the serialized message bytes into a TRADERS message object
    traders_message = optiontrade_pb2.TRADERS()
    print(message_value)
    traders_message.ParseFromString(message_value)
    return traders_message

def consume_messages():
    conf = {
        'bootstrap.servers': "x.x.x.x:9092",
        'group.id': "my_consumer_group",
        'auto.offset.reset': 'earliest',
        'debug': 'all'
    }

    consumer = Consumer(conf)

    topic = 'optiontrade'
    consumer.subscribe([topic])

    try:
        while True:
            msg = consumer.poll(timeout=1.0)

            if msg is None:
                continue
            if msg.error():
                if msg.error().code() == KafkaError._PARTITION_EOF:
                    continue
                else:
                    print(msg.error())
                    break

            # Decode the message value using the decode_message function
            traders_message = decode_message(msg.value())
            
            # Process the decoded message
            print("Received message:")
            print("TRADER_ID:", traders_message.TRADER_ID)
            print("NAME:", traders_message.NAME)
            print("EMAIL:", traders_message.EMAIL)
            print("PHONE_NUMBER:", traders_message.PHONE_NUMBER)
            print("ADDRESS:", traders_message.ADDRESS)

    finally:
        consumer.close()

consume_messages()`

**Comment by whatyouhide** [comment]
Okay the first step here will be to see if we can reproduce this @savhappy 👍
