### ISSUE TITLE
Encoding oneof attribute results in invalid struct

### ISSUE THREAD

**Issue by dpurrington** [elixir-protobuf/protobuf#349]
This code:
```
defmodule Messaging.Shell do
  @moduledoc false
  use Protobuf, protoc_gen_elixir_version: "0.11.0", syntax: :proto3

  oneof :payload, 0

  field :envelope, 1, type: Hub.Messaging.Envelope
  field :payload_type, 2, type: Hub.Messaging.PayloadType, json_name: "payloadType", enum: true
  field :command, 3, type: Hub.Messaging.Command, oneof: 0
  field :command_reply, 4, type: Hub.Messaging.CommandReply, json_name: "commandReply", oneof: 0
  field :event, 5, type: Hub.Messaging.Event, oneof: 0
end

  def create_heartbeat() do
    IO.puts("creating heartbeat")
    shell = %Messaging.Shell{
      envelope: %Messaging.Envelope{
        message_id: UUID.uuid1(),
        created: DateTime.now!("Etc/UTC"),
        sequence_number: 0},
      payload_type: :PAYLOAD_TYPE_EVENT,
      payload: %Messaging.Event{
        event_type: :EVENT_TYPE_NONE,
        reason: "heartbeat"
      }
    }
    IO.inspect(shell)
    Messaging.Shell.encode(shell)

17:49:15.330 [error] Process #PID<0.282.0> terminating
** (exit) an exception was raised:
    ** (Protobuf.EncodeError) Hub.Messaging.Shell#payload should be {key, val}, got: {:ok, %Hub.Messaging.Event{event_type: :EVENT_TYPE_NONE, reason: "heartbeat", __unknown_fields__: []}}
        (protobuf 0.10.0) lib/protobuf/encoder.ex:220: anonymous fn/5 in Protobuf.Encoder.oneof_actual_vals/2
        (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
        (protobuf 0.10.0) lib/protobuf/encoder.ex:26: Protobuf.Encoder.encode_with_message_props/2
        (protobuf 0.10.0) lib/protobuf/encoder.ex:17: Protobuf.Encoder.encode/1
```

From the output, it looks to me like there is an errant return of an encoding call that doesn't extract out the encoded value. I peeked at the relevant code but nothing jumped out at me.

**Comment by dpurrington** [comment]
This test case triggers the error:
```
  test "encodes embedded oneof message without error" do
    Encoder.encode(%OneofProto3{first: 5})
  end
```

**Comment by dpurrington** [comment]
NVM, pebkac. I see that I was constructing the message incorrectly. It should've been 
```
...payload: {:event, %Messaging.Event{...}}
```
