### ISSUE TITLE
(UndefinedFunctionError) function Protobuf.Encoder.encode/2 is undefined or private when running benchmarks

### ISSUE THREAD

**Issue by rparcus** [elixir-protobuf/protobuf#356]
Hi all, just want to report that when running `mix run script/bench.exs` on `main`, I got the following message:

```js
Generated proto_bench app
Operating System: macOS
CPU Information: Apple M1 Max
Number of Available Cores: 10
Available memory: 64 GB
Elixir 1.13.4
Erlang 24.3.4.4

Benchmark suite executing with the following configuration:
warmup: 2 s
time: 20 s
memory time: 5 s
parallel: 1
inputs: google_message1_proto2, google_message1_proto3, google_message2
Estimated total run time: 1.35 min

Benchmarking decode with input google_message1_proto2...
Benchmarking decode with input google_message1_proto3...
Benchmarking decode with input google_message2...

##### With input google_message1_proto2 #####
Name             ips        average  deviation         median         99th %
decode      162.33 K        6.16 μs   ±295.37%        5.92 μs        6.58 μs

Memory usage statistics:

Name      Memory usage
decode         6.73 KB

**All measurements for memory usage were the same**

##### With input google_message1_proto3 #####
Name             ips        average  deviation         median         99th %
decode      161.69 K        6.18 μs   ±231.77%        5.92 μs        6.67 μs

Memory usage statistics:

Name      Memory usage
decode         6.91 KB

**All measurements for memory usage were the same**

##### With input google_message2 #####
Name             ips        average  deviation         median         99th %
decode        2.82 K      354.63 μs    ±33.32%      350.63 μs      385.62 μs

Memory usage statistics:

Name      Memory usage
decode        99.77 KB

**All measurements for memory usage were the same**
Suite saved in external term format at benchmarks/main-ce9a031-decode.benchee


Operating System: macOS
CPU Information: Apple M1 Max
Number of Available Cores: 10
Available memory: 64 GB
Elixir 1.13.4
Erlang 24.3.4.4

Benchmark suite executing with the following configuration:
warmup: 2 s
time: 20 s
memory time: 5 s
parallel: 1
inputs: google_message1_proto2, google_message1_proto3, google_message2
Estimated total run time: 1.35 min

Benchmarking encode with input google_message1_proto2...

11:26:56.376 [error] Task #PID<0.30398.25> started from #PID<0.93.0> terminating
** (UndefinedFunctionError) function Protobuf.Encoder.encode/2 is undefined or private
    (protobuf 0.12.0) Protobuf.Encoder.encode(%Benchmarks.Proto2.GoogleMessage1{field24: false, field7: nil, __unknown_fields__: [], field60: -1, field22: nil, field101: 0, field280: nil, field129: "xxxxxxxxxxxxxxxxxxxxx", field18: "{=Qwfe~#n{", field68: nil, field128: 0, field3: 2066379, field130: 0, field4: "3K+6)#", field5: [], field102: nil, field150: nil, field59: false, field80: false, field16: nil, field67: 1591432, field104: 0, field100: 31, field81: true, field78: nil, field12: true, field271: -1, field103: nil, field13: false, field272: -1, field23: 0, field17: false, field6: 0, field15: %Benchmarks.Proto2.GoogleMessage1SubMessage{__unknown_fields__: [], field1: 25, field12: true, field13: nil, field14: nil, field15: "\"?6PY4]L2c<}~2;\\TVF_w^[@YfbIc*v/N+Z-oYuaWZr4C;5ib|*s@RCBbuvrQ3g(k,N", field16: nil, field19: 2, field2: 36, field20: true, field203: nil, field204: nil, field205: nil, field206: false, field207: nil, field21: 2813090458170031956, ...}, field1: "", field30: false, field2: 8, field9: "10)2uiSuoXL1^)v}icF@>P(j<t#~tz\\lg??S&(<hr7EVs'l{'5`Gohc_(=t eS s{_I?iCwaG]L'*Pu5(&w_:4{~Z", field25: 0, field131: 0, field14: true, field29: 0}, [])
    (benchee 1.0.1) lib/benchee/benchmark/collect/native_time.ex:13: Benchee.Benchmark.Collect.NativeTime.collect/1
    (benchee 1.0.1) lib/benchee/benchmark/runner.ex:246: Benchee.Benchmark.Runner.collect/3
    (benchee 1.0.1) lib/benchee/benchmark/repeated_measurement.ex:39: Benchee.Benchmark.RepeatedMeasurement.determine_n_times/4
    (benchee 1.0.1) lib/benchee/benchmark/runner.ex:182: Benchee.Benchmark.Runner.measure_runtimes/4
    (benchee 1.0.1) lib/benchee/benchmark/runner.ex:107: Benchee.Benchmark.Runner.measure_scenario/2
    (elixir 1.13.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.13.4) lib/task/supervised.ex:34: Task.Supervised.reply/4
Func** (EXIT from #PID<0.93.0>) an exception was raised:
    ** (UndefinedFunctionError) function Protobuf.Encoder.encode/2 is undefined or private
        (protobuf 0.12.0) Protobuf.Encoder.encode(%Benchmarks.Proto2.GoogleMessage1{field24: false, field7: nil, __unknown_fields__: [], field60: -1, field22: nil, field101: 0, field280: nil, field129: "xxxxxxxxxxxxxxxxxxxxx", field18: "{=Qwfe~#n{", field68: nil, field128: 0, field3: 2066379, field130: 0, field4: "3K+6)#", field5: [], field102: nil, field150: nil, field59: false, field80: false, field16: nil, field67: 1591432, field104: 0, field100: 31, field81: true, field78: nil, field12: true, field271: -1, field103: nil, field13: false, field272: -1, field23: 0, field17: false, field6: 0, field15: %Benchmarks.Proto2.GoogleMessage1SubMessage{__unknown_fields__: [], field1: 25, field12: true, field13: nil, field14: nil, field15: "\"?6PY4]L2c<}~2;\\TVF_w^[@YfbIc*v/N+Z-oYuaWZr4C;5ib|*s@RCBbuvrQ3g(k,N", field16: nil, field19: 2, field2: 36, field20: true, field203: nil, field204: nil, field205: nil, field206: false, field207: nil, field21: 2813090458170031956, ...}, field1: "", field30: false, field2: 8, field9: "10)2uiSuoXL1^)v}icF@>P(j<t#~tz\\lg??S&(<hr7EVs'l{'5`Gohc_(=t eS s{_I?iCwaG]L'*Pu5(&w_:4{~Z", field25: 0, field131: 0, field14: true, field29: 0}, [])
        (benchee 1.0.1) lib/benchee/benchmark/collect/native_time.ex:13: Benchee.Benchmark.Collect.NativeTime.collect/1
        (benchee 1.0.1) lib/benchee/benchmark/runner.ex:246: Benchee.Benchmark.Runner.collect/3
        (benchee 1.0.1) lib/benchee/benchmark/repeated_measurement.ex:39: Benchee.Benchmark.RepeatedMeasurement.determine_n_times/4
        (benchee 1.0.1) lib/benchee/benchmark/runner.ex:182: Benchee.Benchmark.Runner.measure_runtimes/4
        (benchee 1.0.1) lib/benchee/benchmark/runner.ex:107: Benchee.Benchmark.Runner.measure_scenario/2
        (elixir 1.13.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
        (elixir 1.13.4) lib/task/supervised.ex:34: Task.Supervised.reply/4

tion: #Function<2.97301739/0 in Benchee.Utility.Parallel.map/2>
    Args: []
```

**Comment by whatyouhide** [comment]
The benchmarks are not currently guaranteed to work, we haven't worked on them in a while. Sorry! Thanks for reporting 💟
